const carta = [
    {
        id : 1,
        name : 'Muñeco Ant-Man',
        description : '“Sólo una pregunta: ¿ya es tarde para cambiar el nombre?”',
        prize : 4000,
        img : 'assets/antman.jpg',
        category : 'marvel',
    } ,
    {
        id : 2,
        name : 'Buzo Marvel',
        description : '"Si estás interesado en lo que haces, ¡eso te hace seguir continuando!".',
        prize : 5000,
        img : 'assets/buzo-marvel.jpg',
        category : 'marvel',
    } ,
    {
        id : 3,
        name : 'Comics',
        description : 'Elige tu comic.',
        prize : 1200,
        img : 'assets/comics.jpg',
        category: 'marvel',
    } ,
    {
        id : 4,
        name : 'Figuras Avengers',
        description : ' Ant-Man + Iron Man + Capitan America. “Si no podemos proteger la Tierra, puedes estar seguro de que la vengaremos” ',
        prize : 10000,
        img : 'assets/conjunto-deFiguras-Avengers.jpg',
        category : 'marvel',
    } ,
    {
        id : 5,
        name : 'Cuadro Iron Man',
        description : '"Puedes quitarme mi casa, todos mis trucos y trajes, pero hay una cosa que jamás podrás quitarme: Yo soy Iron Man."',
        prize : 3500,
        img : 'assets/cuadro-ironman.jpg',
        category : 'marvel',
    } ,
    {
        id : 6,
        name : 'Disfraz Spiderman',
        description : '"Un gran poder conlleva una gran responsabilidad"',
        prize : 12000,
        img : 'assets/Disfraz-spiderman.jpg',
        category : 'marvel',
    } ,
    {
        id : 7,
        name : 'Muñeco Deadpool',
        description : '“Si tu pierna izquierda es Acción de gracias, y la derecha es Navidad, ¿te puedo visitar entre las fiestas?”',
        prize : 4500,
        img : 'assets/figura-deadpool.jpg',
        category : 'marvel',
    } ,
    {
        id : 8,
        name : 'Figura Dr Strange',
        description : '"¿Sabes cuál es el más grande regalo que alguien puede recibir en toda su vida? El mejor regalo que podemos recibir es tener la oportunidad, una sola vez en nuestras vidas, de hacer la diferencia." — Doctor la estranio :c',
        prize : 10000,
        img : 'assets/figura-DrLaestranio.jpg',
        category : 'marvel',
    } ,
    {
        id : 9,
        name : 'Muñeco Groot',
        description : '"Yo soy Groot"',
        prize : 700,
        img : 'assets/groot.jpg',
        category : 'marvel',
    } ,
    {
        id : 10,
        name : 'Traje real de Iron Man',
        description : 'Sí, sí. Es el traje real de Iron Man porque somos la mejor tienda 😎 Precio en USD. "No es suficiente estar en contra, tienes que estar a favor de algo mejor."',
        prize : 200000000,
        img : 'assets/ironman-trajereal.jpg',
        category : 'Mmrvel',
    } ,
    {
        id : 11,
        name : 'Martillo de Thor',
        description : '"Yo soy Thor, hijo de Odín y mientras haya vida en mi pecho… No se me ocurre más nada que decir. ¿Estás listo para morir?"',
        prize : 40000,
        img : 'assets/martilloThor-tamañoReal.jpg',
        category : 'marvel',
    } ,
    {
        id : 12,
        name : 'Mouse Capitán América',
        description : '"Haría esto todo el día","Incluso cuando no tenía nada, tenía a Bucky🧡🧡🧡"',
        prize : 2500,
        img : 'assets/mouse-capAmerica.jpg',
        category : 'DC',
    } ,
    {
        id : 13,
        name : 'Vinilo Iron Man',
        description : '"¿Es mejor ser temido o respetado? Yo digo, ¿es mucho pedir que sea ambos?"',
        prize : 15000,
        img : 'assets/vinilo-ironman.jpg',
        category : 'marvel',
    } ,
    {
        id : 14,
        name : 'Figuras DC',
        description : 'Batman + Superman + Mujer maravilla. “Dime, ¿Sangras? Sangrarás. “',
        prize : 35000,
        img : 'assets/figuras-dc.jpg',
        category : 'DC',
    } ,
    {
        id : 15,
        name : 'Lego Batman + Lego Superman',
        description : '"Batman: Es hora de que aprendas lo que significa ser un hombre.Superman: ¡Quédate abajo!  Si lo quisiera, ya estarías muerto."',
        prize : 4500,
        img : 'assets/legos.jpg',
        category : 'DC',
    } ,
    {
        id : 16,
        name : 'Figura Mujer maravilla',
        description : '"Estoy dispuesta a luchar por los que no pueden luchar por sí mismos"',
        prize : 50000,
        img : 'assets/figura-wonderwoman.jpg',
        category : 'DC',
    } ,
    {
        id : 17,
        name : 'Funko Harley Quuin',
        description : '"¿No te gusto? Bien. No me hagas perder el tiempo entonces."',
        prize : 5000,
        img : 'assets/harley-quuin.jpeg',
        category : 'DC',
    } ,
];